server:
  port: 8084
spring:
  cloud:
    gateway:
      routes:
      - id: fsh-house
        uri: lb://fsh-house
        predicates:
        - Path=/house/**
  application:
    name: rabbit-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://rabbit:123456@master:8761/eureka/




